### ISSUE TITLE
Pair must be provided for Spread endpoint

### ISSUE THREAD

**Issue by Willgg** [jonatack/kraken_ruby_client#14]
https://github.com/jonatack/kraken_ruby_client/blob/0f9990cbd4d093caf057d0eeb43ff3a60b98a1a9/lib/kraken_ruby_client/client.rb#L160

**Comment by jonatack** [comment]
Thanks @Willgg! I apologize for not seeing your issue earlier.

Please feel free to open a pull request for this or any other fixes and improvements.

Contributions are very welcome!

**Comment by jonatack** [comment]
The command works fine for me:
```ruby
require 'kraken_ruby_client'
client = Kraken::Client.new
client.spread('xbtusd')
client.spread('xbtusd', since: 1611698949)
```
