### ISSUE TITLE
Ruby Version

### ISSUE THREAD

**Issue by PaulRivier** [jonatack/kraken_ruby_client#20]
Hi,

what is the minimum Ruby version required please ?  README says 2.4, but gemspec enforces 2.6. Thank you.

**Comment by jonatack** [comment]
Hi @PaulRivier, 2.4 should work. I think I bumped the gemspec to 2.6 because it is now the oldest supported version according to https://www.ruby-lang.org.

**Comment by PaulRivier** [comment]
Thank you very much for your quick answer. 
I'm on a Debian stable box, and my Ruby is simply the version packaged on this distro (2.5). Although it may very well be able to run your package, bundle (and gem) will refuse to install it because of this gemspec line. There may be way to force it, but I don't know them.
In my opinion, if the package works with older ruby, it is fine to leave low bounds, and as far as I know it is common practice to be as permissive as possible.

Regards,

**Comment by jonatack** [comment]
I don't recommend using an unsupported end of life Ruby (best to install a supported version for more safety and security fixes), but feel free to change the gemspec file locally on your machine for your needs.
