### ISSUE TITLE
Private API not working with 2FA

### ISSUE THREAD

**Issue by ronnyworm** [jonatack/kraken_ruby_client#21]
Hi,
first things first: thank you so much for developing this library!
I tried to get it working today and all the public requests are working but I'm getting an {"error"=>["EAPI:Invalid signature"]}

Kraken forces 2FA for some months now. I tried to use the library without any changes but that didn't work.
Then I configured a 2FA API-Key on the website but I can't figure out how to make this work either.

What can I do about that?

Maybe this helps somehow:
https://github.com/JKorf/Kraken.Net/issues/9

Best regards

**Comment by jonatack** [comment]
It's working fine for me, and I use 2FA since years. I don't think 2FA has anything to do with the API. You just need to provide a valid API key and secret as described in the README. Make sure you gave the API key the permissions that you need.

```
require 'kraken_ruby_client'
client = Kraken::Client.new(api_key: 'YOUR_API_KEY', api_secret: 'YOUR_API_SECRET')
```
