### ISSUE TITLE
XBT pairings got renamed

### ISSUE THREAD

**Issue by krtschmr** [jonatack/kraken_ruby_client#22]
https://support.kraken.com/hc/en-us/articles/201893658-Currency-pairs-available-for-trading-on-Kraken

recently renamed Doge and Bitcoin pairings

the Readme/Docs don't reflect that

**Comment by jonatack** [comment]
Indeed, it seems this just changed in the past couple of days and the tests no longer pass.

**Comment by krtschmr** [comment]
yes, they announced it last week

**Comment by jonatack** [comment]
Did some testing, and it looks like via the API, XBT still works in all cases, but BTC does not.  So it seems best to leave it as it is currently, at least for now.

**Comment by jonatack** [comment]
(That said, feel free to make a pull request to update the README when BTC works throughout the API like XBT does, or if XBT no longer works.)
